Souvenir list
minorleaguegrayonassociates/GrayonSlam pull request #34
Opened 2019-04-07 05:54 UTC by ChrisRzech

Closes #32 

### Key features
* Widget that displays a souvenir from any stadium
* Able to show a spinbox (future use in trip planning)
* Able to obtain the value of each spinbox

### Future Improvements
* none

### Notes
Changing the spinbox's value to minimum value removes the item from the list. This is to support the trip planning's cart when the user wants to remove an item from the cart.

2019-04-07 20:20 UTC, Roger-Chavez approved these changes

2019-04-10 06:26 UTC, Roger-Chavez approved these changes

2019-04-12 04:08 UTC, WakkaTrout requested changes

2019-04-12 04:08 UTC, WakkaTrout commented on src/widgets/souvenirlist.cpp
> + * a @a QListWidgetItem at a given row and the return the result.
Say that it **dynamic casts a QListWidgetItem at a given row into a SouvenirListItem and then returns the result**

2019-04-12 04:12 UTC, WakkaTrout approved these changes
Everything looks good my dude, Land that List!

2019-04-12 04:14 UTC, merged