Dashboard view
minorleaguegrayonassociates/GrayonSlam pull request #60
Opened 2019-04-24 03:40 UTC by ChrisRzech

Closes #39 

### Key features
* Dashboard view usable in `MainWindow`
* Splash message system that randomizes whenever the view resets
* Image slideshow that changes image every few seconds (currently 2 seconds)

### Future Improvements
* Definitely more content, looks empty

### Notes
none

2019-04-25 06:05 UTC, Roger-Chavez requested changes
Please change splash messages to be something baseball related. For example baseball trivia.

2019-04-25 06:11 UTC, WakkaTrout requested changes

2019-04-25 06:11 UTC, WakkaTrout commented on src/widgets/imageslideshow.cpp
> +
Just squish these 3 lines and you good

2019-04-26 02:36 UTC, yosmo78 approved these changes
looks good, works goods, even smells good

2019-04-26 02:42 UTC, WakkaTrout approved these changes
I can't find anything bad and it runs fine on my computer, so approved

2019-04-26 06:31 UTC, Roger-Chavez approved these changes

2019-04-26 06:31 UTC, merged